### ISSUE TITLE
UI & Interaction

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#1]
Discussion for the UI pages and user interaction

**Comment by TheQuietPotato** [comment]
Designing a mock up of what the Home page may look like (Desktop V) thoughts?

![Idex_mock_1](https://user-images.githubusercontent.com/2602263/66255605-7c121980-e77d-11e9-939d-07d305a6d62d.jpg)

**Comment by dosaki** [comment]
That looks pretty good!

I know we're not looking at colours right now, but have you had a look at https://colorhunt.co/ or https://color.adobe.com/create for colour palettes?

How would the mobile version look like?

Also, when interacting with the Fixtures on the bottom left, where does it take you?

**Comment by TheQuietPotato** [comment]
Did a little more mock up work this morning thought about how it may translate to mobile.
Also, the fixtures display I guess would just be another prompt for the user to either log in or register from this page?
![Display Mock Up](https://user-images.githubusercontent.com/2602263/66267329-97396380-e827-11e9-9d5c-e3ff78997f10.jpg)
@dosaki I did have a look at the color pallets you linked but had a hard time finding a decent one to go with the green color of the image, let me know if you have any suggestions.

**Comment by dosaki** [comment]
How about https://colorhunt.co/palette/158293 ?

**Comment by TheQuietPotato** [comment]
Okay officially lost down the rabbit hole.... done a re-design, incorporated a color theme....thoughts? 
![Idex_mock_2](https://user-images.githubusercontent.com/2602263/66431333-b8f73e00-ea13-11e9-9ec0-837fbb8bbcdf.jpg)

**Comment by dosaki** [comment]
I like it!

**Comment by neilmusgrove** [comment]
These look really great! It's got a very stylish and professional look to it. I merged a PR on some ui from @AMIllan75 this morning because we didn't have anything else at that point so there may need to be some discussion on a final look. Not sure if you've seen them but I added some public domain flag svg images today as well for use. Are these mock ups in HTML or is it some sort of graphics product? Just wondering how much work there is to make this 'real'.

**Comment by dosaki** [comment]
We can get a rough draft that looks a bit like it and then tune it further later.

We should also make sure to move all the HTML files into [`views`](https://github.com/msc-dtss/super6assignment/tree/master/views) and turn them into `ejs` files.

**Comment by MikeKeightley** [comment]
I like it! It looks slick, with nice and easy navigation, in terms of placement etc.  I was wondering the same as Neil as to how you mocked them up - and the effort involved into brining it to life so to speak. I think the colour palette works really well too

**Comment by dosaki** [comment]
@AMIllan75 to push his changes tomorrow.

Closing this for now.

**Comment by TheQuietPotato** [comment]
Basic wireframe for the "Betting" page.

https://wireframe.cc/NS1ud7

**Comment by TheQuietPotato** [comment]
Thoughts on an SVG logo?
![image](https://user-images.githubusercontent.com/2602263/67718925-b790b400-f9c8-11e9-8b19-feaa1c4e6677.png)
