### ISSUE TITLE
Mock JSON database

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#12]

**Comment by MikeKeightley** [comment]
I've added a super6db folder with the associate JSON files into the project - some of the collections I've just populated with empty strings so far just to give an idea of the design - my thinking here was that these would be ones populated (mostly) by user input or business logic/calculations.

**Comment by dosaki** [comment]
Yeah, it looks like `matchResults` and `points` could be nested in another collection.

Looks good though!

**Comment by MikeKeightley** [comment]
Yeah, they were the last two that I built....must have been done in a panic! :)
