### ISSUE TITLE
Ability to vote on all games in a round

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#16]

**Comment by TheQuietPotato** [comment]
@dosaki Had a little bit of time tonight to try and figure out the structure of a createBet function. Initially  I just wanted to create a factory function in JS to get the basic functionality right, then can transfer over to "insertOne()".  Probably tomorrow night.

![image](https://user-images.githubusercontent.com/2602263/66869884-3bde4280-ef98-11e9-8820-ed013b7851c4.png)

**Comment by TheQuietPotato** [comment]
Just posting here a screenshot of tonight's scribbling looking at this issue - will continue tomorrow

![image](https://user-images.githubusercontent.com/2602263/66870407-4cdb8380-ef99-11e9-9832-ca7f7f3f7460.png)

**Comment by dosaki** [comment]
maybe something more like this?
```javascript

const createBet = () => {
    const bet = {
        "betId": betId,
        "gameId": gameId
    }
}
```

**Comment by TheQuietPotato** [comment]
Better? 
![image](https://user-images.githubusercontent.com/2602263/67042337-9655db00-f11f-11e9-8453-de87ed9d980b.png)

**Comment by dosaki** [comment]
Yes!

**Comment by dosaki** [comment]
Related to #18
