### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#18]
Depends on #5 

Users need a section to know what rounds they have voted on (and how they've voted).
Users can vote on rounds whenever they are available but can also edit them before the round starts.
This lets us distribute the load on the server over time.. or something like that.

Also needs a place to show their winnings and such.

Relates to #18

**Comment by neilmusgrove** [comment]
Getting there with showing a grid of fixtures, to be populated with predictions, results etc. Layout could be improved if there is time but I think a simple grid works in the first instance.

**Comment by dosaki** [comment]
AJAX calls to poll server for results and auto-update with winnings

**Comment by dosaki** [comment]
Relates to #39
