### ISSUE TITLE
System(s) Architecture(s)

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#2]

**Comment by neilmusgrove** [comment]
We don't want to overcomplicate the architecture design - there will be little benefit, however I do think we should have a data access layer so that the business logic is not coupled directly to mongo db.

**Comment by dosaki** [comment]
Keep it simple: [architecture suggestion](https://github.com/msc-dtss/super6assignment/raw/master/docs/images/architecture.png).

Need to define what's in that API. Should be relate to those model elements though

**Comment by dosaki** [comment]
Also see #7
