### ISSUE TITLE
Fix bets/play to only give you the games for the current active round

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#28]
Game Rounds need to have a valid date range to vote on.

This is to ensure a user can't vote on rounds that aren't active yet and also so they don't vote on past rounds.

It will also make the code to fix `/bets/play` simpler.

**Comment by TheQuietPotato** [comment]
@dosaki Is this a bug or am I missing something? I was taking a look at the bets page this morning and I was getting some unexpected games showing up when I put in a November date as my query. Looked in the degbugger and if you see the formatted date is returning Oct??

![image](https://user-images.githubusercontent.com/2602263/68192292-05994f00-ffa9-11e9-961a-5447e15a5ce4.png)

**Comment by dosaki** [comment]
This looks like a bug

**Comment by dosaki** [comment]
Looks like a bug!

**Comment by TheQuietPotato** [comment]
@dosaki Getting some strange results with the date query on bets. For example when i query 2019/10/01 i get 8 game results, but when i query 2019/10/02 i get 0 game results. This is strange as we do have games with dates of 2019/10/05 in the games collection. My best guess at the moment is how the $gt mongo operator reads the date value?

![image](https://user-images.githubusercontent.com/2602263/68395068-f2cc7900-0166-11ea-856f-dcc55889823c.png)

**Comment by dosaki** [comment]
That **is** strange.

If you can't figure it out, I'll have a look at this.
