### ISSUE TITLE
Redirect the user to a meaningful page after registering

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#30]
1) Login the user automatically?
2) Redirect the user to their profile, or the play page or main page?

**Comment by MikeKeightley** [comment]
@dosaki @neilmusgrove Is there a 'quick win' for this, such as just passing the newly created details through to the login service for example?  Or would it be more appropriate to display the log in box, with a message saying that registration has been successful, please log in?

**Comment by dosaki** [comment]
I think the best way to go about this is to forward the request to the login controller with the same info if the register action was successful.

What do you think, @neilmusgrove ?

**Comment by neilmusgrove** [comment]
I would probably set the session values and then forward to the next page. Do whichever you will find easiest @MikeKeightley.

**Comment by MikeKeightley** [comment]
@neilmusgrove @dosaki I've just set it to set the session up when after the user is created, and the redirect to /bets/play - which seems to work fine.  No need to log in again really.  Will push tomorrow if that sounds like an adequate solution?

**Comment by dosaki** [comment]
Sounds good!
