### ISSUE TITLE
Use the actual user information on /bets/history/, on /bets/play/ and on posting to /bets/

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#38]
At the moment in [`routes/bets`](https://github.com/msc-dtss/super6assignment/blob/master/routes/bets.js), `/bets/play` route isn't taking user information into account and `/bets/history` is using a hardcoded ID:
```javascript
    const bets = await betsService.allForUser(db, new ObjectId('5d9dea063935915c6861feaf')); //TODO - Use real user id
```

Posting to `/bets/` also needs to be protected.

**Comment by dosaki** [comment]
Related to #5 and #18 and #16

**Comment by MikeKeightley** [comment]
@dosaki @neilmusgrove Is this still outstanding?  I added some session persistence to these the other day, and also it looks like Neil has made some changes to them last night too?

**Comment by dosaki** [comment]
Good point. I'll have to check

**Comment by neilmusgrove** [comment]
I am taking care of history because I'm making a lot of changes to that.  @MikeKeightley can you look at the others but if you're struggling let me know because I can take some off your hands if necessary.
