### ISSUE TITLE
Allow users to edit their bets if round has not started yet

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#47]
From the profile page (#18)

**Comment by neilmusgrove** [comment]
At the minute you can go back to the bet page and place a whole new set of bets. We should block re-entry unless it's in the form of a proper edit mode.

**Comment by dosaki** [comment]
We should ensure that going back to the betting page makes you edit your existing bet instead?

**Comment by TheQuietPotato** [comment]
@dosaki Instead of being able to edit it directly on the profile page? Makes sense I guess as a lot of the code is pretty much there

**Comment by neilmusgrove** [comment]
You could add a very easy edit mode if you warn on the bet page you've already placed a bet and then simply delete any existing bet for the round when a new one is placed.
