### ISSUE TITLE
Bets not being injected into the database

### ISSUE THREAD

**Issue by TheQuietPotato** [msc-dtss/super6assignment#49]
Bets do not yet get injected into the "bets" collection

**Comment by dosaki** [comment]
I'll work on this. I'm in the area

**Comment by dosaki** [comment]
This is working fine for me on the latest code.
Can you let me know what you've done?

**Comment by neilmusgrove** [comment]
I've pushed a slight change where the user id wasn't set correctly but apart from that it looks to be working

**Comment by dosaki** [comment]
Fixed on master!
