### ISSUE TITLE
Wrong password when logging in causes the page to hang

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#52]
@MikeKeightley can you have a look at this?

**Comment by MikeKeightley** [comment]
Only just seen this @dosaki - Probably something to do with the error catching and the redirect I would imagine.  I'd like it to just display a message to user that the password was incorrect really, and let the user attempt to enter it again.

**Comment by MikeKeightley** [comment]
Should this work for displaying the error message to the user?  I'm seeing an 'error is not defined' message when trying to test. @dosaki @neilmusgrove 
![image](https://user-images.githubusercontent.com/55582938/69494105-80220400-0eaf-11ea-9e1e-19efda5b2205.png)

**Comment by dosaki** [comment]
Are you passing `error` to the view?

**Comment by MikeKeightley** [comment]
I'm trying to add the above into the header.ejs..... which already has:

<% const hasError = typeof error === 'undefined' ? false : !!error %>

Or do i need to pass this somewhere else?

**Comment by dosaki** [comment]
Then when `error` is `undefined` it will be `false`.
This means you won'y be able to do `error.httpCode` or `error.message` since a boolean does not have that.

**Comment by MikeKeightley** [comment]
Ahh, is that because of the '!!'? Are you still free later to help me get this sorted - think i'm just getting confused!

**Comment by dosaki** [comment]
No problem.

I've got 15 minutes before having to go make some lunch. Want to have a chat?
